### ISSUE TITLE
can someone help me getting black screen when starting my mirror 

### ISSUE THREAD

**Issue by Frimagik** [mykle1/MMM-Lunartic#26]
> magicmirror@2.16.0 start /home/pi/MagicMirror
> electron js/electron.js

[23.08.2021 08:30.21.811] [LOG]   Starting MagicMirror: v2.16.0
[23.08.2021 08:30.21.839] [LOG]   Loading config ...
[23.08.2021 08:30.21.857] [LOG]   Loading module helpers ...
[23.08.2021 08:30.21.863] [LOG]   No helper found for module: alert.
[23.08.2021 08:30.22.410] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.22.413] [LOG]   Module helper loaded: updatenotification
[23.08.2021 08:30.22.416] [LOG]   No helper found for module: clock.
[23.08.2021 08:30.27.493] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.27.495] [LOG]   Module helper loaded: calendar
[23.08.2021 08:30.27.499] [LOG]   No helper found for module: compliments.
[23.08.2021 08:30.27.502] [LOG]   No helper found for module: weather.
[23.08.2021 08:30.27.612] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.27.613] [LOG]   Module helper loaded: newsfeed
[23.08.2021 08:30.27.617] [LOG]   No helper found for module: MMM-APOD.
[23.08.2021 08:30.27.639] [ERROR] WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
[23.08.2021 08:30.27.641] [LOG]   Loading module helpers ...
[23.08.2021 08:30.27.642] [LOG]   No helper found for module: alert.
[23.08.2021 08:30.27.644] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.27.645] [LOG]   Module helper loaded: updatenotification
[23.08.2021 08:30.27.647] [LOG]   No helper found for module: clock.
[23.08.2021 08:30.27.649] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.27.650] [LOG]   Module helper loaded: calendar
[23.08.2021 08:30.27.652] [LOG]   No helper found for module: compliments.
[23.08.2021 08:30.27.654] [LOG]   No helper found for module: weather.
[23.08.2021 08:30.27.656] [LOG]   Initializing new module helper ...
[23.08.2021 08:30.27.657] [LOG]   Module helper loaded: newsfeed
[23.08.2021 08:30.27.659] [LOG]   No helper found for module: MMM-APOD.
[23.08.2021 08:30.27.665] [ERROR] App threw an error during load
[23.08.2021 08:30.27.670] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
[23.08.2021 08:30.27.674] [ERROR] Whoops! There was an uncaught exception...
[23.08.2021 08:30.27.690] [ERROR] Error: Cannot find module 'request'
Require stack:
- /home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js:8:17)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-Lunartic/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}
[23.08.2021 08:30.27.695] [ERROR] MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[23.08.2021 08:30.27.696] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[23.08.2021 08:30.31.005] [LOG]   Launching application.
[23.08.2021 08:30.49.769] [LOG]   Shutting down server...
[23.08.2021 08:30.49.827] [LOG]   Stopping module helper: updatenotification
[23.08.2021 08:30.49.831] [LOG]   Stopping module helper: calendar
[23.08.2021 08:30.49.835] [LOG]   Stopping module helper: newsfeed
[23.08.2021 08:30.49.838] [LOG]   Stopping module helper: updatenotification
[23.08.2021 08:30.49.843] [LOG]   Stopping module helper: calendar
[23.08.2021 08:30.49.846] [LOG]   Stopping module helper: newsfeed

**Comment by rabbit83ka** [comment]
[Have a look in the MagicMirror Forum](https://forum.magicmirror.builders/topic/15666/add-request-to-modules.) You have to install "request" manually.

**Comment by KristjanESPERANTO** [comment]
@rabbit83ka is right. You need to go to the modules folder and run `npm install request` or `npm install`.
